"""empty message

Revision ID: 10e36e027145
Revises: 
Create Date: 2020-10-04 09:46:54.438014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e36e027145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('item',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('listkey', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['listkey'], ['list.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('list')
    # ### end Alembic commands ###
